// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ShortUrl    string
	OriginalUrl string
	ClickCount  int32
	CreatedAt   pgtype.Timestamptz
}
