// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const deleteURL = `-- name: DeleteURL :exec
DELETE FROM urls WHERE short_url = $1
`

func (q *Queries) DeleteURL(ctx context.Context, shortUrl string) error {
	_, err := q.db.Exec(ctx, deleteURL, shortUrl)
	return err
}

const getCount = `-- name: GetCount :one
SELECT click_count FROM urls WHERE short_url = $1
`

func (q *Queries) GetCount(ctx context.Context, shortUrl string) (int32, error) {
	row := q.db.QueryRow(ctx, getCount, shortUrl)
	var click_count int32
	err := row.Scan(&click_count)
	return click_count, err
}

const getOriginalURL = `-- name: GetOriginalURL :one
SELECT original_url FROM urls WHERE short_url = $1
`

func (q *Queries) GetOriginalURL(ctx context.Context, shortUrl string) (string, error) {
	row := q.db.QueryRow(ctx, getOriginalURL, shortUrl)
	var original_url string
	err := row.Scan(&original_url)
	return original_url, err
}

const incrementCount = `-- name: IncrementCount :exec
UPDATE urls SET click_count = click_count + 1 WHERE short_url = $1
`

func (q *Queries) IncrementCount(ctx context.Context, shortUrl string) error {
	_, err := q.db.Exec(ctx, incrementCount, shortUrl)
	return err
}

const saveURL = `-- name: SaveURL :exec
INSERT INTO urls (short_url, original_url) VALUES ($1, $2)
`

type SaveURLParams struct {
	ShortUrl    string
	OriginalUrl string
}

func (q *Queries) SaveURL(ctx context.Context, arg SaveURLParams) error {
	_, err := q.db.Exec(ctx, saveURL, arg.ShortUrl, arg.OriginalUrl)
	return err
}
